"""Gate S: subsidy persistence — how long must it hold, and how long has it been seen to hold.

    python gates.py [--pages 20]

``docs/PROTOCOL.md`` Class S. Registered 2026-09-14, before this was written and before any cadence,
direction or hazard figure was computed.

**This gate does not forecast persistence, and any output claiming to is void.** It measures three
observable things and compares two quantities in months. ``NO VERDICT`` is a pre-committed, expected
outcome (AXIOMS G12/A1).

Nothing here trades or quotes (F3).
"""

from __future__ import annotations

import argparse
import collections
import datetime as dt
import random

from kairos.nullworld import ALPHA, FPR_TAIL_ALPHA, POWER_FLOOR, _binomial_tail
from kairos.persistence import (
    annual_hazard_bound, detect_succession, maker_take, months_between,
    parse_schedule_version, rule_of_three, separation_auc, take_pair, weighted_direction,
    weighted_instability,
)
from gatem import open_universe, quote

#: Pre-committed before the real cohorts were built, and validated on the null worlds below.
AUC_FLOOR = 0.90

#: Relative change in the maker's take above which terms are not "stable".
STABILITY_TOL = 0.05

PERMUTATIONS = 400
NULL_REPS = 200

#: Gate M2's measured `(posted size, capital, net/yr)`, capital hurdle already charged.
#: Size is a curve, not a point (C11) - the payback question has a different answer at each rung,
#: and quoting only the largest was the defect recorded as Pass 35.
M2_BY_SIZE = ((25, 4_875.0, 2_024.0), (100, 19_500.0, 8_096.0),
              (500, 97_500.0, 40_257.0), (2_000, 390_000.0, 139_450.0))

#: A generic contract rate. A parameter of the payback curve, not a claim about anybody.
PERSON_MONTH_COST = 12_000.0
BUILD_MONTHS = (0.0, 1.0, 3.0, 6.0)

#: Registered minimum. One revision is not a cadence.
MIN_PAIRS = 2


def epoch(iso: str | None) -> float | None:
    if not iso:
        return None
    try:
        return dt.datetime.fromisoformat(iso.replace("Z", "+00:00")).timestamp()
    except (ValueError, TypeError):
        return None


# ----------------------------------------------------------------------------------------------
# Null worlds. Generated by a process that does NOT share the detector's assumption that a higher
# version suffix means a later cohort (AXIOMS G14) - `world_reversed` negates it outright.
# ----------------------------------------------------------------------------------------------

def world_no_structure(rng: random.Random, n: int = 120) -> dict:
    """One unversioned family. There is no succession to find, so none may be reported."""
    return {("alpha_fees", 1): [rng.uniform(0.0, 1e8) for _ in range(n)]}


def world_interleaved(rng: random.Random, n: int = 60) -> dict:
    """Two versions drawn from one distribution, labels assigned independently of date.

    This is the confound the real data may contain: coexisting variants rather than a succession.
    """
    dates = [rng.uniform(0.0, 1e8) for _ in range(2 * n)]
    rng.shuffle(dates)
    return {("alpha_fees", 1): dates[:n], ("alpha_fees", 2): dates[n:]}


def world_reversed(rng: random.Random, n: int = 60) -> dict:
    """Version numbers assigned in REVERSE temporal order - the detector's premise negated."""
    old = [rng.uniform(0.0, 1e7) for _ in range(n)]
    new = [rng.uniform(5e7, 6e7) for _ in range(n)]
    return {("alpha_fees", 1): new, ("alpha_fees", 2): old}


def world_separated(rng: random.Random, n: int = 60) -> dict:
    """POWER. A real succession, which the detector must actually find."""
    old = [rng.uniform(0.0, 1e7) for _ in range(n)]
    new = [rng.uniform(5e7, 6e7) for _ in range(n)]
    return {("alpha_fees", 1): old, ("alpha_fees", 2): new}


FPR_WORLDS = (("no_structure", world_no_structure), ("interleaved", world_interleaved),
              ("reversed_versions", world_reversed))


def run_nulls(rng: random.Random) -> bool:
    print(f"\n[1/4] Null gate - {NULL_REPS} replications per world, "
          f"AUC floor {AUC_FLOOR}, alpha {ALPHA}")
    ok = True

    for name, make in FPR_WORLDS:
        hits = sum(
            1 for _ in range(NULL_REPS)
            if detect_succession(make(rng), auc_floor=AUC_FLOOR, alpha=ALPHA, rng=rng,
                                 n_permutations=PERMUTATIONS)
        )
        rate = hits / NULL_REPS
        tail = _binomial_tail(hits, NULL_REPS, ALPHA)
        good = tail >= FPR_TAIL_ALPHA
        ok &= good
        print(f"      FPR   {name:<20} {hits:>3}/{NULL_REPS} = {rate:>6.1%}  "
              f"tail {tail:.4f}  {'PASS' if good else 'FAIL'}")

    hits = sum(
        1 for _ in range(NULL_REPS)
        if detect_succession(world_separated(rng), auc_floor=AUC_FLOOR, alpha=ALPHA, rng=rng,
                             n_permutations=PERMUTATIONS)
    )
    power = hits / NULL_REPS
    good = power >= POWER_FLOOR
    ok &= good
    print(f"      POWER {'separated':<20} {hits:>3}/{NULL_REPS} = {power:>6.1%}  "
          f"floor {POWER_FLOOR:.0%}    {'PASS' if good else 'FAIL'}")

    # The signed-mean trap: churn must NOT read as stable, and a genuinely flat programme must.
    churn_unstable = stable_unstable = 0
    for _ in range(NULL_REPS):
        churn = [(rng.uniform(0.005, 0.02), rng.uniform(0.005, 0.02)) for _ in range(6)]
        flat = []
        for _ in range(6):
            t = rng.uniform(0.005, 0.02)
            flat.append((t, t))
        w = [1.0] * 6
        if (weighted_instability(churn, w) or 0.0) > STABILITY_TOL:
            churn_unstable += 1
        if (weighted_instability(flat, w) or 0.0) > STABILITY_TOL:
            stable_unstable += 1
    c_rate, s_rate = churn_unstable / NULL_REPS, stable_unstable / NULL_REPS
    c_good = c_rate >= POWER_FLOOR
    s_tail = _binomial_tail(stable_unstable, NULL_REPS, ALPHA)
    s_good = s_tail >= FPR_TAIL_ALPHA
    ok &= c_good and s_good
    print(f"      POWER {'churn_is_unstable':<20} {churn_unstable:>3}/{NULL_REPS} = "
          f"{c_rate:>6.1%}  floor {POWER_FLOOR:.0%}    {'PASS' if c_good else 'FAIL'}")
    print(f"      FPR   {'flat_reads_stable':<20} {stable_unstable:>3}/{NULL_REPS} = "
          f"{s_rate:>6.1%}  tail {s_tail:.4f}  {'PASS' if s_good else 'FAIL'}")

    # The signed statistic on the same churn, shown rather than argued.
    churn = [(0.010, 0.015), (0.010, 0.005)] * 3
    w = [1.0] * 6
    print(f"      exhibit: churn direction {weighted_direction(churn, w):+.6f} "
          f"(reads 'no change'), instability {weighted_instability(churn, w):.1%} (reads churn)")
    print(f"\n      NULL GATE: {'PASS' if ok else 'FAIL'}")
    return ok


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--pages", type=int, default=20)
    args = ap.parse_args()
    rng = random.Random(20260914)

    print("=" * 94)
    print("GATE S - SUBSIDY PERSISTENCE (required horizon vs observed stability)")
    print("=" * 94)
    print("  This gate does NOT forecast persistence. It compares two quantities in months.")
    print("  Hazard is an UPPER BOUND from zero observed withdrawals, never an estimate.")
    print("  NOTHING IS TRADED OR QUOTED")

    if not run_nulls(rng):
        print("\n  WITHHELD - the estimator failed its own null gate. No real-data reading is")
        print("  licensed (AXIOMS A7). Fix the estimator, not the worlds (A8).")
        return 1

    print(f"\n[2/4] Sweeping fee-enabled markets for creation-date cohorts...", flush=True)
    print("      NOTE: band and tick-room filters are NOT applied here. They select on")
    print("      tradeability, which correlates with recency, and would manufacture separation.")
    cohorts: dict[tuple[str, int], list[float]] = {}
    terms: dict[tuple[str, int], tuple[float, float, int]] = {}
    eligible = collections.Counter()
    census = collections.Counter()
    for m in open_universe(args.pages):
        if not m.get("feesEnabled"):
            census["fees_disabled"] += 1
            continue
        fs = m.get("feeSchedule") or {}
        key = parse_schedule_version(m.get("feeType"))
        created = epoch(m.get("createdAt"))
        if key is None or created is None or "rate" not in fs:
            census["unusable"] += 1
            continue
        cohorts.setdefault(key, []).append(created)
        terms[key] = (float(fs["rate"]), float(fs.get("rebateRate", 0.0)),
                      int(fs.get("exponent", 1)))
        census["cohorted"] += 1
        # Gate M2's tradeable universe, metadata only, used solely to weight the revision test.
        q = quote(m)
        if not isinstance(q, str):
            spread, tick, _, _ = q
            if spread / tick > 1.0 + 1e-9:
                eligible[key] += 1

    now = dt.datetime.now(dt.timezone.utc).timestamp()
    print(f"      markets cohorted {census['cohorted']}   fee-disabled {census['fees_disabled']}"
          f"   unusable {census['unusable']}")
    print(f"\n      {'schedule':<24} {'n':>5} {'M2-elig':>8} {'exp':>4} {'take':>8} "
          f"{'oldest':>9} {'newest':>9}")
    for key in sorted(cohorts, key=lambda k: (k[0], k[1])):
        d = cohorts[key]
        rate, reb, exp = terms[key]
        flag = "" if exp == 1 else "  <- exponent 2: take NOT on the same scale"
        print(f"      {key[0] + '_v' + str(key[1]):<24} {len(d):>5} {eligible[key]:>8} {exp:>4} "
              f"{maker_take(rate, reb):>8.4f} "
              f"{months_between(max(d), now):>7.1f}mo "
              f"{months_between(min(d), now):>7.1f}mo{flag}")

    print(f"\n[3/4] Succession, direction, instability")
    pairs = detect_succession(cohorts, auc_floor=AUC_FLOOR, alpha=ALPHA, rng=rng,
                              n_permutations=PERMUTATIONS)
    multi = {f for f, _ in cohorts}
    families_multi = [f for f in sorted(multi)
                      if sum(1 for g, _ in cohorts if g == f) > 1]
    print(f"      families with >1 version : {families_multi or 'none'}")
    for f in families_multi:
        vs = sorted(v for g, v in cohorts if g == f)
        for a, b in zip(vs, vs[1:]):
            auc = separation_auc(cohorts[(f, a)], cohorts[(f, b)])
            print(f"      {f} v{a}->v{b}: AUC {auc:.4f} "
                  f"({'separated' if auc and auc >= AUC_FLOOR else 'INTERLEAVED - not a succession'})")
    print(f"      succession pairs established : {len(pairs)}")

    direction = instability = None
    if pairs:
        takes, weights = [], []
        for p in pairs:
            try:
                pair = take_pair(terms[(p.family, p.older)], terms[(p.family, p.newer)])
            except ValueError as exc:
                print(f"      {p.family} v{p.older}->v{p.newer}: WITHHELD - {exc}")
                continue
            takes.append(pair)
            # Rebate dollars at risk, proportional to eligible markets x take (equal-fills assumed).
            weights.append(eligible[(p.family, p.newer)] * pair[1])
            print(f"      {p.family} v{p.older}->v{p.newer}: take "
                  f"{takes[-1][0]:.4f} -> {takes[-1][1]:.4f}  AUC {p.auc:.3f} p={p.p_value:.4f}")
        direction = weighted_direction(takes, weights)
        instability = weighted_instability(takes, weights)
        print(f"      weighted direction   {direction:+.6f} "
              f"({'CUT' if direction < 0 else 'held or raised'})")
        print(f"      weighted instability {instability:.2%} "
              f"(tolerance {STABILITY_TOL:.0%})")

    print(f"\n[4/4] Hazard bound and payback")
    prog_start = min(min(d) for d in cohorts.values())
    prog_months = months_between(prog_start, now)
    sched_months = sum(months_between(min(d), now) for d in cohorts.values())
    for label, n in (("programme-months (one decision)", prog_months),
                     ("schedule-months (assumes independence)", sched_months)):
        monthly = rule_of_three(max(1, int(n)))
        print(f"      {label:<42} n={n:>7.1f}  monthly bound <= {monthly:>6.1%}  "
              f"annual <= {annual_hazard_bound(monthly):>6.1%}")
    governing = annual_hazard_bound(rule_of_three(max(1, int(prog_months))))
    print(f"      GOVERNING annual withdrawal hazard bound: <= {governing:.1%}")
    print("      (the programme-level count governs: one decision withdraws every schedule)")

    # C11 twice over: build cost is a curve AND so is size. Holding size at 2,000 contracts was a
    # defect in this gate's first run - it hid that a small operator cannot repay any build cost
    # inside the window the subsidy has been observed to exist (CORRECTIONS.md Pass 35).
    stability = prog_months
    print(f"\n      Payback in months. 'X' exceeds the {stability:.1f}-month observed programme")
    print(f"      life, i.e. the build never repays inside any window the subsidy has been seen")
    print(f"      to hold. Capital is Gate M2's, at ${PERSON_MONTH_COST:,.0f} per person-month.")
    print(f"\n      {'size':>6} {'capital':>10} {'net/yr':>9} {'ROC':>6}" +
          "".join(f"{str(int(b)) + 'mo build':>12}" for b in BUILD_MONTHS if b > 0))
    for size, cap, net in M2_BY_SIZE:
        monthly = net / 12.0
        cells = ""
        for bm in BUILD_MONTHS:
            if bm <= 0:
                continue
            pb = bm * PERSON_MONTH_COST / monthly
            cells += f"{format(pb, '.1f') + 'mo' + ('  X' if pb > stability else '   '):>12}"
        print(f"      {size:>6,} {'$' + format(cap, ',.0f'):>10} "
              f"{'$' + format(net, ',.0f'):>9} {net / cap:>5.1%}{cells}")

    smallest = M2_BY_SIZE[0]
    print(f"\n      At the smallest measured size (${smallest[1]:,.0f} of capital) even ONE")
    print(f"      person-month of build takes "
          f"{PERSON_MONTH_COST / (smallest[2] / 12.0):.0f} months to repay.")

    print(f"\n{'=' * 94}\nVERDICT\n{'=' * 94}")
    print(f"  observed stability (programme age) : {prog_months:.1f} months")
    print(f"  payback at 6 person-months of build: "
          f"{6 * PERSON_MONTH_COST / (M2_BY_SIZE[-1][2] / 12.0):.1f} months at "
          f"{M2_BY_SIZE[-1][0]:,} contracts / ${M2_BY_SIZE[-1][1]:,.0f}, but "
          f"{6 * PERSON_MONTH_COST / (M2_BY_SIZE[0][2] / 12.0):.0f} months at "
          f"{M2_BY_SIZE[0][0]:,}")
    print(f"  annual withdrawal hazard           : <= {governing:.1%} (bound, not estimate)")

    # The registered rule: "Version suffixes are not temporal succession, OR FEWER THAN 2
    # succession pairs -> NO VERDICT." One revision is not a cadence; an interval cannot be
    # estimated from a single event. This branch governs whatever the other statistics say.
    if len(pairs) < MIN_PAIRS:
        print(f"\n  GATE S: NO VERDICT on persistence. {len(pairs)} succession pair(s) "
              f"established, against a registered minimum of {MIN_PAIRS}.")
        print("  One revision is not a cadence: an interval cannot be estimated from a single")
        print("  event, and the registered rule anticipated exactly this. The API exposes each")
        print("  market's CURRENT feeType and createdAt, never when a schedule was introduced or")
        print("  reassigned, and `open_universe` sees only OPEN markets - so every cohort is")
        print("  truncated by resolution and earlier versions may be invisible entirely.")
        print("  This is not a failure of the hypothesis, and it is NOT licence to proceed as")
        print("  though the gate had passed.")
        if direction is not None:
            print(f"\n  Recorded but NOT a verdict: the one established revision held the")
            print(f"  maker's take EXACTLY flat (direction {direction:+.6f}, instability "
                  f"{instability:.2%}) while the taker fee rose 0.03 -> 0.05.")
            print("  The venue took the whole increase. One observation, and not a trend.")
    elif direction is not None and direction < 0:
        print("\n  GATE S: REFUTED as durable. Revisions CUT the maker's take on the dollars")
        print("  that carry the exposure. Class M2 is a decaying promotion, not a strategy.")
    elif instability is not None and instability > STABILITY_TOL:
        print("\n  GATE S: NOT REFUTED, but terms are UNSTABLE - the take moved without being cut.")
        print("  Repricing risk, not removal risk, and it must be carried as such.")
    else:
        print("\n  GATE S: NOT REFUTED. Payback sits inside observed stability and no revision")
        print("  cut the maker's take. Class M2 remains SUBSIDY-DEPENDENT - never an edge.")

    print("\n  Unmodelled: the venue's finances, budget and intentions; withdrawal without warning")
    print("  (a single decision has no cadence); regulatory change; competitive response.")
    print("  The hazard bound rests on ZERO observed withdrawals and bounds nothing tightly.")
    print("=" * 94)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
